api:
  prefix: api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_website
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true

logging:
  level:
    root: info
jwt:
  expiration: 2592000
